// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RapidLaunch.Areas.Identity.Models;


namespace RapidLaunch.Migrations
{
    [DbContext(typeof(RapidLaunchDbContext))]
    [Migration("20200205202932_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("RapidLaunch.Models.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .IsRequired();

                    b.Property<string>("AddressLine2");

                    b.Property<string>("City")
                        .IsRequired();

                    b.Property<int>("ContactID");

                    b.Property<string>("Country")
                        .IsRequired();

                    b.Property<string>("PostalCode")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired();

                    b.HasKey("AddressID");

                    b.HasIndex("ContactID")
                        .IsUnique();

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("RapidLaunch.Models.Contact", b =>
                {
                    b.Property<int>("ContactID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailAddress")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.HasKey("ContactID");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("RapidLaunch.Models.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GroupName")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("RapidLaunch.Models.DepartmentHistory", b =>
                {
                    b.Property<int>("StaffID");

                    b.Property<int>("DepartmentID");

                    b.Property<int>("ShiftID");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("StaffID", "DepartmentID", "ShiftID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("ShiftID");

                    b.ToTable("DepartmentHistories");
                });

            modelBuilder.Entity("RapidLaunch.Models.Launch", b =>
                {
                    b.Property<int>("LaunchID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LaunchPadID");

                    b.Property<int>("LaunchProjectID");

                    b.Property<int>("LaunchStatusID");

                    b.Property<DateTime?>("LaunchedDateTime")
                        .HasColumnType("DateTime2");

                    b.Property<DateTime>("PlannedDateTime")
                        .HasColumnType("DateTime2");

                    b.Property<int>("RocketID");

                    b.HasKey("LaunchID");

                    b.HasIndex("LaunchPadID");

                    b.HasIndex("LaunchProjectID");

                    b.HasIndex("LaunchStatusID");

                    b.HasIndex("RocketID");

                    b.ToTable("Launches");
                });

            modelBuilder.Entity("RapidLaunch.Models.LaunchDestination", b =>
                {
                    b.Property<int>("LaunchDestinationID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasMaxLength(255);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("LaunchDestinationID");

                    b.ToTable("LaunchDestinations");
                });

            modelBuilder.Entity("RapidLaunch.Models.LaunchPad", b =>
                {
                    b.Property<int>("LaunchPadID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LaunchPadCode")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<int>("LaunchPadStatusID");

                    b.Property<int>("LaunchSiteID");

                    b.HasKey("LaunchPadID");

                    b.HasIndex("LaunchPadStatusID");

                    b.HasIndex("LaunchSiteID");

                    b.ToTable("LaunchPads");
                });

            modelBuilder.Entity("RapidLaunch.Models.LaunchPadStatus", b =>
                {
                    b.Property<int>("LaunchPadStatusID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.HasKey("LaunchPadStatusID");

                    b.ToTable("LaunchPadStatuses");
                });

            modelBuilder.Entity("RapidLaunch.Models.LaunchProgram", b =>
                {
                    b.Property<int>("LaunchProjectID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int>("LaunchDestinationID");

                    b.Property<string>("Name");

                    b.HasKey("LaunchProjectID");

                    b.HasIndex("LaunchDestinationID");

                    b.ToTable("LaunchPrograms");
                });

            modelBuilder.Entity("RapidLaunch.Models.LaunchSite", b =>
                {
                    b.Property<int>("LaunchSiteID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BuildDate");

                    b.Property<string>("Country");

                    b.Property<string>("Location");

                    b.HasKey("LaunchSiteID");

                    b.ToTable("LaunchSites");
                });

            modelBuilder.Entity("RapidLaunch.Models.LaunchStatus", b =>
                {
                    b.Property<int>("LaunchStatusID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("LaunchStatusID");

                    b.ToTable("LaunchStatus");
                });

            modelBuilder.Entity("RapidLaunch.Models.Manufacturer", b =>
                {
                    b.Property<int>("ManufacturerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ManufacturerID");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("RapidLaunch.Models.PayHistory", b =>
                {
                    b.Property<int>("StaffID");

                    b.Property<DateTime>("PayDate")
                        .HasColumnType("date");

                    b.Property<decimal?>("Allowance")
                        .HasColumnType("money");

                    b.Property<double>("Percentage");

                    b.HasKey("StaffID", "PayDate");

                    b.ToTable("PayHistories");
                });

            modelBuilder.Entity("RapidLaunch.Models.PayRate", b =>
                {
                    b.Property<int>("PayRateID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Rank")
                        .HasMaxLength(25);

                    b.HasKey("PayRateID");

                    b.ToTable("PayRates");
                });

            modelBuilder.Entity("RapidLaunch.Models.Person", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("ContactID");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("Gender")
                        .IsRequired();

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("MiddleName");

                    b.Property<string>("NationalInsuranceNumber")
                        .IsRequired();

                    b.Property<int>("StaffID");

                    b.Property<string>("Title")
                        .HasMaxLength(8);

                    b.HasKey("PersonID");

                    b.HasIndex("ContactID");

                    b.HasIndex("StaffID")
                        .IsUnique();

                    b.ToTable("People");
                });

            modelBuilder.Entity("RapidLaunch.Models.Position", b =>
                {
                    b.Property<int>("JobTitleID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DepartmentID");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("PayRateID");

                    b.HasKey("JobTitleID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("PayRateID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("RapidLaunch.Models.Provider", b =>
                {
                    b.Property<int>("ProviderID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<DateTime?>("EstablishDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("ProviderID");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("RapidLaunch.Models.Rocket", b =>
                {
                    b.Property<int>("RocketID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("ManufactureDate")
                        .HasColumnType("date");

                    b.Property<int>("ProviderID");

                    b.Property<int>("RocketModelID");

                    b.Property<int>("RocketStatusID");

                    b.HasKey("RocketID");

                    b.HasIndex("ProviderID");

                    b.HasIndex("RocketModelID");

                    b.HasIndex("RocketStatusID");

                    b.ToTable("Rockets");
                });

            modelBuilder.Entity("RapidLaunch.Models.RocketCategory", b =>
                {
                    b.Property<int>("RocketCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("RocketCategoryID");

                    b.ToTable("RocketCategories");
                });

            modelBuilder.Entity("RapidLaunch.Models.RocketModel", b =>
                {
                    b.Property<int>("RocketModelID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<double?>("Diameter");

                    b.Property<double?>("Height");

                    b.Property<int>("ManufacturerID");

                    b.Property<double?>("Mass");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<double?>("PayloadGTO");

                    b.Property<double?>("PayloadLEO");

                    b.Property<int?>("ProviderID");

                    b.Property<int>("RocketCategoryID");

                    b.HasKey("RocketModelID");

                    b.HasIndex("ManufacturerID");

                    b.HasIndex("ProviderID");

                    b.HasIndex("RocketCategoryID");

                    b.ToTable("RocketModels");
                });

            modelBuilder.Entity("RapidLaunch.Models.RocketStatus", b =>
                {
                    b.Property<int>("RocketStatusID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("RocketStatusID");

                    b.ToTable("RocketStatuses");
                });

            modelBuilder.Entity("RapidLaunch.Models.Shift", b =>
                {
                    b.Property<int>("ShiftID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("ShiftID");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("RapidLaunch.Models.Staff", b =>
                {
                    b.Property<int>("StaffID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("date");

                    b.Property<int>("JobTitleID");

                    b.HasKey("StaffID");

                    b.HasIndex("JobTitleID");

                    b.ToTable("Staff");
                });

            modelBuilder.Entity("RapidLaunch.Models.Address", b =>
                {
                    b.HasOne("RapidLaunch.Models.Contact", "Contact")
                        .WithOne("Address")
                        .HasForeignKey("RapidLaunch.Models.Address", "ContactID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RapidLaunch.Models.DepartmentHistory", b =>
                {
                    b.HasOne("RapidLaunch.Models.Department", "Department")
                        .WithMany("DepartmentHistories")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RapidLaunch.Models.Shift", "Shift")
                        .WithMany("DepartmentHistories")
                        .HasForeignKey("ShiftID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RapidLaunch.Models.Staff", "Staff")
                        .WithMany("DepartmentHistories")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RapidLaunch.Models.Launch", b =>
                {
                    b.HasOne("RapidLaunch.Models.LaunchPad", "LaunchPad")
                        .WithMany("Launches")
                        .HasForeignKey("LaunchPadID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RapidLaunch.Models.LaunchProgram", "LaunchProgram")
                        .WithMany("Launches")
                        .HasForeignKey("LaunchProjectID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RapidLaunch.Models.LaunchStatus", "LaunchStatus")
                        .WithMany("Launches")
                        .HasForeignKey("LaunchStatusID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RapidLaunch.Models.Rocket", "Rocket")
                        .WithMany("Launches")
                        .HasForeignKey("RocketID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RapidLaunch.Models.LaunchPad", b =>
                {
                    b.HasOne("RapidLaunch.Models.LaunchPadStatus", "LaunchPadStatus")
                        .WithMany("LaunchPads")
                        .HasForeignKey("LaunchPadStatusID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RapidLaunch.Models.LaunchSite", "LaunchSite")
                        .WithMany("LaunchPads")
                        .HasForeignKey("LaunchSiteID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RapidLaunch.Models.LaunchProgram", b =>
                {
                    b.HasOne("RapidLaunch.Models.LaunchDestination", "LaunchDestination")
                        .WithMany("LaunchPrograms")
                        .HasForeignKey("LaunchDestinationID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RapidLaunch.Models.PayHistory", b =>
                {
                    b.HasOne("RapidLaunch.Models.Staff", "Staff")
                        .WithMany("PayHistories")
                        .HasForeignKey("StaffID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RapidLaunch.Models.Person", b =>
                {
                    b.HasOne("RapidLaunch.Models.Contact", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactID");

                    b.HasOne("RapidLaunch.Models.Staff", "Staff")
                        .WithOne("Person")
                        .HasForeignKey("RapidLaunch.Models.Person", "StaffID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RapidLaunch.Models.Position", b =>
                {
                    b.HasOne("RapidLaunch.Models.Department", "Department")
                        .WithMany("JobTitles")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RapidLaunch.Models.PayRate", "PayRate")
                        .WithMany("Positions")
                        .HasForeignKey("PayRateID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RapidLaunch.Models.Rocket", b =>
                {
                    b.HasOne("RapidLaunch.Models.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RapidLaunch.Models.RocketModel", "RocketModel")
                        .WithMany("Rockets")
                        .HasForeignKey("RocketModelID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RapidLaunch.Models.RocketStatus", "RocketStatus")
                        .WithMany("Rockets")
                        .HasForeignKey("RocketStatusID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RapidLaunch.Models.RocketModel", b =>
                {
                    b.HasOne("RapidLaunch.Models.Manufacturer", "Manufacturer")
                        .WithMany("RocketModels")
                        .HasForeignKey("ManufacturerID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RapidLaunch.Models.Provider", "Provider")
                        .WithMany("RocketModels")
                        .HasForeignKey("ProviderID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RapidLaunch.Models.RocketCategory", "RocketCategory")
                        .WithMany("RocketModels")
                        .HasForeignKey("RocketCategoryID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RapidLaunch.Models.Staff", b =>
                {
                    b.HasOne("RapidLaunch.Models.Position", "JobTitle")
                        .WithMany("Staff")
                        .HasForeignKey("JobTitleID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
